# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: synergychat-web
  type: ClusterIP
  ports:
    - name: api-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
---

